### ISSUE TITLE
Support http proxy

### ISSUE THREAD

**Issue by tesths** [mgleon08/instagram-crawler#1]
If the network is can't browser instagram, the program will stuck.
Just show
```
failed to connect: No route to host - connect(2) for "www.instagram.com" port 443
```
Even if use terminal proxy.
Maybe instagram-crawler can add option support http proxy or socks proxy.

**Comment by mgleon08** [comment]
Thanks your feedback.
I created new branch `https://github.com/mgleon08/instagram-crawler/tree/proxy` for proxy, you can clone to testing, use `bin/instagram-crawler -u <user_name> -p http://example.com` (port: 8080)
I will push new version, if it works.

**Comment by tesths** [comment]
I do not use this new version, but I check source code, find the port is not variable.(Maybe I am mistake)
Can you set port as variable either?

**Comment by mgleon08** [comment]
ok, please pull again.
Try `bin/instagram-crawler -u <user_name> -P http://example.com -p 1234`

**Comment by tesths** [comment]
I already try it! Everything went well! Fantastic!!
Very thank you!
There has ruby gem about instagram data eventually!

**Comment by mgleon08** [comment]
Greate! I pushed new version, you can reinstall!

**Comment by aditya-citrix** [comment]
I tried instagram-crawler -u xyz -P 45.55.9.218 -p 8080 IP is from the random proxy list. I am getting HttpError: 400 Bad Request. What am I doing wrong?
